network_params:
  genesis_delay: 120
participants:
  # First participant will be used by Diva
  - el_client_type: geth
    cl_client_type: teku
    cl_split_mode_enabled: true
  - el_client_type: geth
    cl_client_type: nimbus
    # it will receive (total validators - diva validators)
diva_params:
  verify_fee_recipient: true
  nodes: 5
  total_validator_count: 65
  diva_validator_count: 1 # First parcicipant's validator
